### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by lainverse** [erkle64/FastEscalators#1]
Unless I misunderstood what it supposed to modify, personal escalators seem to go up and down at the same speed, no matter the multiplier.

Game version 0.5.2.14962 (current test branch)
Plugin installed with Mod Manager. I have a couple other plugins like FastMiner and Duplicationeer installed with the same mod manager and they work flawlessly.

Player.log attached. Not sure if there's anything useful, though.
[log.zip](https://github.com/user-attachments/files/15750335/log.zip)

**Comment by erkle64** [comment]
Are you trying to use the escalator mod to speed up elevators?

**Comment by lainverse** [comment]
🤦🏼‍♂️
Yes, that's exactly what I did.
And forgot escalators exists in the first place.

Ok, can this be a feature request, then? :)

**Comment by erkle64** [comment]
Unfortunately the speed of the personal elevator is in native code, so I can't change it.

**Comment by lainverse** [comment]
Thank you and sorry for false reporting a bug.
